jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t kalemat/01-crear-pedido:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push kalemat/01-crear-pedido:latest

      - name: Deploy to Railway
        run: railway up --deployment fe8f3e58-0c97-4b9e-83dc-17f7ac5a1198 --yes
