name: Build and Deploy to Railway

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de la imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crear-pedido:latest

      - name: Instalar Railway CLI
        run: curl -sSL https://railway.app/install.sh | sh

      - name: Deploy en Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service docker-crear --detach
