name: Build and Deploy to Docker Hub and Railway

on:
  push:
    branches:
      - main  # Cambia si usas otra rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: kalemat/01-crear-pedido:latest

    - name: Trigger Railway deploy
      run: |
        curl -X POST https://backboard.railway.app/webhook/deploy/${{ secrets.RAILWAY_DEPLOY_HOOK }}
